version: "3"
services:
  backend:
    container_name: gogosing-springboot
    build:
      context: ./backend
      args:
        SERVER_MODE: dev
    ports:
      - 8082:8082
  frontend:
    container_name: gogosing-react
    build:
      context: ./frontend
      dockerfile: Dockerfile
    ports:
      - 3002:3002
    volumes:
      - /usr/src/app/node_modules
      - ./frontend:/usr/src/app
    stdin_open: true
    depends_on:
	      - backend